use std::cell::{Cell, OnceCell, RefCell};
use std::process::Child;
use std::sync::{
    atomic::{
        AtomicBool,
        Ordering,
    },
    mpsc::{self, Receiver},
    Arc,
    Mutex,
};
use std::thread;

use objc2::rc::Retained;
use objc2::runtime::{AnyObject, ProtocolObject, Sel};
use objc2::{
    define_class,
    msg_send,
    sel,
    AnyThread,
    ClassType,
    DefinedClass,
    MainThreadOnly,
};

use objc2_app_kit::{
    NSApplication,
    NSApplicationActivationPolicy,
    NSApplicationDelegate,
    NSBackingStoreType,
    NSBezelStyle,
    NSBox,
    NSBoxType,
    NSButton,
    NSCellImagePosition,
    NSColor,
    NSEvent,
    NSEventModifierFlags,
    NSEventType,
    NSImage,
    NSProgressIndicator,
    NSProgressIndicatorStyle,
    NSResponder,
    NSText,
    NSTextAlignment,
    NSTextField,
    NSTitlePosition,
    NSTrackingArea,
    NSTrackingAreaOptions,
    NSView,
    NSWindow,
    NSWindowDelegate,
    NSWindowStyleMask,
    NSWorkspace,
};

#[cfg(debug_assertions)]
use objc2_app_kit::NSBitmapImageFileType;

#[cfg(debug_assertions)]
use objc2_foundation::NSDictionary;

use objc2_foundation::{
    ns_string,
    MainThreadMarker,
    NSNotification,
    NSObject,
    NSObjectProtocol,
    NSPoint,
    NSRect,
    NSSize,
    NSString,
    NSTimer,
    NSURL,
};

use crate::logging;
use crate::worker;
use crate::state::AppState;


// Development builds only: `--ui-self-test` runs AppDelegate::run_ui_self_test.
#[cfg(debug_assertions)]
const UI_SELF_TEST_FLAG: &str = "--ui-self-test";

#[cfg(debug_assertions)]
thread_local! {
    static UI_SELF_TEST: Cell<bool> = const { Cell::new(false) };
}


// -----------------------------------------------------------------------------
// Keyboard policy
//
// Decided once per key-down event, before AppKit dispatches it:
//
// - A key held down repeats. A repeated Space/Return must not activate a button
//   again: because focus follows the primary slot across state changes, a held
//   Space would otherwise press Search, then the Cancel that replaced it, then
//   Search again, many times a second. One physical press is one activation.
//
// - Plain L (either case, so Caps Lock works) opens the logs folder whenever
//   the window is active, whichever control has focus.
//
// - Nothing is intercepted while the user is typing into an editable control.
// -----------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum KeyFocus {
    // No control has keyboard focus.
    Window,

    Button,

    // An editable text control (or its field editor).
    TextInput,

    Other,
}


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum KeyDecision {
    // Let AppKit handle the event normally.
    PassThrough,

    // Swallow: a repeat of a key that already acted once.
    SuppressRepeat,

    OpenLogsFolder,

    // Return / Enter on a focused button: click it. AppKit only does this by
    // itself for Space.
    ActivateFocusedButton,
}


struct KeyInput<'a> {
    // The key's characters, ignoring modifiers such as Shift.
    characters: &'a str,

    // Generated by the key being held down, not by a new press.
    is_repeat: bool,

    // Command, Control, or Option is held.
    has_command_modifier: bool,

    focus: KeyFocus,
}


// The name of a key that activates a focused button.
fn activation_key_name(characters: &str) -> Option<&'static str> {
    match characters {
        " " => Some("Space"),
        "\r" => Some("Return"),
        "\u{3}" => Some("Enter"),
        _ => None,
    }
}


fn key_decision(input: &KeyInput<'_>) -> KeyDecision {
    // Typing is never intercepted.
    if input.focus == KeyFocus::TextInput {
        return KeyDecision::PassThrough;
    }

    if input.has_command_modifier {
        return KeyDecision::PassThrough;
    }

    if input.characters.eq_ignore_ascii_case("l") {
        // Holding L opens the folder once, not once per repeat.
        return if input.is_repeat {
            KeyDecision::SuppressRepeat
        } else {
            KeyDecision::OpenLogsFolder
        };
    }

    // Only a button that actually has focus can be activated. With nothing
    // focused these keys do nothing: there is no default button.
    if input.focus != KeyFocus::Button {
        return KeyDecision::PassThrough;
    }

    match activation_key_name(input.characters) {
        None => KeyDecision::PassThrough,

        Some(_) if input.is_repeat => KeyDecision::SuppressRepeat,

        // AppKit activates a focused button on Space itself.
        Some("Space") => KeyDecision::PassThrough,

        Some(_) => KeyDecision::ActivateFocusedButton,
    }
}


// -----------------------------------------------------------------------------
// Main window
//
// An NSWindow that applies the keyboard policy above to its key-down events.
// Everything else is stock NSWindow behaviour.
// -----------------------------------------------------------------------------

struct MainWindowIvars {
    // Whether the current key hold has already been reported, so a held key
    // logs one Verbose line rather than one per repeat.
    repeat_reported: Cell<bool>,
}


define_class!(
    #[unsafe(super(NSWindow))]
    #[thread_kind = MainThreadOnly]
    #[name = "PGCMainWindow"]
    #[ivars = MainWindowIvars]
    struct MainWindow;

    unsafe impl NSObjectProtocol for MainWindow {}

    impl MainWindow {
        #[unsafe(method(sendEvent:))]
        fn send_event(
            &self,
            event: &NSEvent,
        ) {
            if event.r#type() == NSEventType::KeyDown
                && self.handle_key_down(event)
            {
                return;
            }

            let _: () = unsafe {
                msg_send![super(self), sendEvent: event]
            };
        }
    }
);


impl MainWindow {
    fn new(
        mtm: MainThreadMarker,
        content_rect: NSRect,
        style: NSWindowStyleMask,
    ) -> Retained<Self> {
        let this =
            Self::alloc(mtm).set_ivars(MainWindowIvars {
                repeat_reported: Cell::new(false),
            });

        unsafe {
            msg_send![
                super(this),
                initWithContentRect: content_rect,
                styleMask: style,
                backing: NSBackingStoreType::Buffered,
                defer: false,
            ]
        }
    }


    // Returns true when the event was consumed.
    fn handle_key_down(
        &self,
        event: &NSEvent,
    ) -> bool {
        let characters =
            event
                .charactersIgnoringModifiers()
                .map(|characters| characters.to_string())
                .unwrap_or_default();

        let modifiers =
            event.modifierFlags();

        let input = KeyInput {
            characters: &characters,

            is_repeat: event.isARepeat(),

            has_command_modifier:
                modifiers.contains(NSEventModifierFlags::Command)
                    || modifiers.contains(NSEventModifierFlags::Control)
                    || modifiers.contains(NSEventModifierFlags::Option),

            focus: self.key_focus(),
        };

        // A new press starts a new hold.
        if !input.is_repeat {
            self.ivars().repeat_reported.set(false);
        }

        let decision =
            key_decision(&input);

        // Verbose provenance for a key that is about to activate a button.
        let activates =
            !input.is_repeat
                && input.focus == KeyFocus::Button
                && matches!(
                    decision,
                    KeyDecision::PassThrough | KeyDecision::ActivateFocusedButton
                );

        if let (true, Some(key)) = (activates, activation_key_name(&characters)) {
            self.notify_delegate(
                sel!(buttonActivatedByKey:),
                &NSString::from_str(key),
            );
        }

        match decision {
            KeyDecision::PassThrough => false,

            KeyDecision::ActivateFocusedButton => {
                if let Some(first_responder) = self.firstResponder() {
                    if let Some(button) = first_responder.downcast_ref::<NSButton>() {
                        // Same as a click, including the brief pressed look.
                        unsafe {
                            button.performClick(None);
                        }
                    }
                }

                true
            }

            KeyDecision::SuppressRepeat => {
                // Report the first swallowed repeat of a hold, and only for
                // keys that would have activated a control.
                if let Some(key) = activation_key_name(&characters) {
                    if !self.ivars().repeat_reported.replace(true) {
                        self.notify_delegate(
                            sel!(keyRepeatSuppressed:),
                            &NSString::from_str(key),
                        );
                    }
                }

                true
            }

            KeyDecision::OpenLogsFolder => {
                self.notify_delegate(
                    sel!(openLogsFromKeyboard:),
                    self,
                );

                true
            }
        }
    }


    // What kind of control currently has keyboard focus.
    fn key_focus(&self) -> KeyFocus {
        let Some(first_responder) = self.firstResponder() else {
            return KeyFocus::Window;
        };

        let window: &NSResponder =
            self;

        if std::ptr::eq(&*first_responder, window) {
            return KeyFocus::Window;
        }

        if first_responder.downcast_ref::<NSButton>().is_some() {
            return KeyFocus::Button;
        }

        // A text field being edited makes its field editor (an NSText) the
        // first responder.
        if let Some(text) = first_responder.downcast_ref::<NSText>() {
            if text.isEditable() {
                return KeyFocus::TextInput;
            }
        }

        KeyFocus::Other
    }


    fn notify_delegate(
        &self,
        action: Sel,
        argument: &AnyObject,
    ) {
        let Some(delegate) = self.delegate() else {
            return;
        };

        let delegate: &AnyObject =
            delegate.as_ref();

        if delegate.class().responds_to(action) {
            // performSelector:withObject: returns an object; it is not used.
            let _: *mut AnyObject = unsafe {
                msg_send![delegate, performSelector: action, withObject: argument]
            };
        }
    }
}


// -----------------------------------------------------------------------------
// Hover feedback for the main buttons
//
// A standard push button that lightens while the pointer is over it. Shape,
// size, title, pressed look, and the keyboard focus ring are all AppKit's own.
// Hover is a faint rounded overlay on top of the bezel, in the same neutral
// fill as the utility shelf, shown and hidden by pointer enter/exit events
// only (no polling). Because the overlay is added to whatever AppKit draws,
// a pressed button under the pointer is visibly stronger than a hovered one.
// -----------------------------------------------------------------------------

define_class!(
    #[unsafe(super(NSButton))]
    #[thread_kind = MainThreadOnly]
    #[name = "PGCHoverButton"]
    struct HoverButton;

    unsafe impl NSObjectProtocol for HoverButton {}

    impl HoverButton {
        #[unsafe(method(mouseEntered:))]
        fn mouse_entered(
            &self,
            _event: &NSEvent,
        ) {
            self.set_hovered(true);
        }


        #[unsafe(method(mouseExited:))]
        fn mouse_exited(
            &self,
            _event: &NSEvent,
        ) {
            self.set_hovered(false);
        }


        // A button hidden while hovered never receives mouseExited, so clear
        // the tint here rather than showing it stale when it reappears.
        #[unsafe(method(viewDidHide))]
        fn view_did_hide(&self) {
            self.set_hovered(false);

            let _: () = unsafe {
                msg_send![super(self), viewDidHide]
            };
        }


        // A button shown under a stationary pointer (for example Cancel
        // replacing Search for Host after a click) gets no mouseEntered until
        // the pointer moves, so check where the pointer is.
        #[unsafe(method(viewDidUnhide))]
        fn view_did_unhide(&self) {
            let _: () = unsafe {
                msg_send![super(self), viewDidUnhide]
            };

            self.set_hovered(
                self.pointer_is_inside()
            );
        }
    }
);


impl HoverButton {
    // The same button `NSButton::buttonWithTitle_target_action` makes, as a
    // HoverButton, returned as the NSButton the rest of the UI works with.
    fn push_button(
        title: &NSString,
        target: &AnyObject,
        action: Sel,
    ) -> Retained<NSButton> {
        let button: Retained<HoverButton> = unsafe {
            msg_send![
                Self::class(),
                buttonWithTitle: title,
                target: target,
                action: action,
            ]
        };

        // Follows the button's visible area automatically, so it never needs
        // rebuilding when the button moves or resizes.
        let tracking = unsafe {
            NSTrackingArea::initWithRect_options_owner_userInfo(
                NSTrackingArea::alloc(),
                NSRect::new(
                    NSPoint::new(0.0, 0.0),
                    NSSize::new(0.0, 0.0),
                ),
                NSTrackingAreaOptions::MouseEnteredAndExited
                    | NSTrackingAreaOptions::ActiveInActiveApp
                    | NSTrackingAreaOptions::InVisibleRect,
                Some(&button),
                None,
            )
        };

        button.addTrackingArea(&tracking);


        // The hover overlay. Its frame is set each time it is shown, from the
        // button's size at that moment.
        let overlay =
            NSBox::initWithFrame(
                NSBox::alloc(button.mtm()),
                hover_overlay_frame(button.bounds().size),
            );

        overlay.setBoxType(NSBoxType::Custom);
        overlay.setTitlePosition(NSTitlePosition::NoTitle);
        overlay.setBorderWidth(0.0);
        overlay.setCornerRadius(HOVER_CORNER_RADIUS);
        overlay.setFillColor(&hover_fill_colour());

        overlay.setHidden(true);

        // The overlay does not handle the mouse, so clicks on it continue up
        // to the button as usual.
        button.addSubview(&overlay);

        Retained::into_super(button)
    }


    fn hover_overlay(&self) -> Option<Retained<NSBox>> {
        self.subviews()
            .iter()
            .find_map(|view| view.downcast::<NSBox>().ok())
    }


    fn set_hovered(
        &self,
        hovered: bool,
    ) {
        if let Some(overlay) = self.hover_overlay() {
            if hovered {
                overlay.setFrame(
                    hover_overlay_frame(self.bounds().size)
                );
            }

            overlay.setHidden(!hovered);
        }
    }


    fn pointer_is_inside(&self) -> bool {
        let Some(window) = self.window() else {
            return false;
        };

        let pointer =
            self.convertPoint_fromView(
                window.mouseLocationOutsideOfEventStream(),
                None,
            );

        let bounds =
            self.bounds();

        pointer.x >= bounds.origin.x
            && pointer.y >= bounds.origin.y
            && pointer.x < bounds.origin.x + bounds.size.width
            && pointer.y < bounds.origin.y + bounds.size.height
    }
}


// Matches the corner rounding of a standard push button closely enough that
// the overlay reads as the button itself brightening.
const HOVER_CORNER_RADIUS: f64 = 6.0;


// The same faint, appearance-aware fill as the utility shelf.
fn hover_fill_colour() -> Retained<NSColor> {
    NSColor::quaternaryLabelColor()
}


// Height of a regular-size push button's visible bezel. The button's frame is
// taller than what it draws; the bezel is centred vertically and spans the
// full width.
const PUSH_BUTTON_BEZEL_HEIGHT: f64 = 24.0;


// The part of a push button of `size` that its bezel occupies.
fn hover_overlay_frame(size: NSSize) -> NSRect {
    let height =
        PUSH_BUTTON_BEZEL_HEIGHT.min(size.height);

    NSRect::new(
        NSPoint::new(
            0.0,
            (size.height - height) / 2.0,
        ),
        NSSize::new(size.width, height),
    )
}


// -----------------------------------------------------------------------------
// Objective-C instance variables
// -----------------------------------------------------------------------------

struct AppDelegateIvars {
    window: OnceCell<Retained<NSWindow>>,
    host_label: OnceCell<Retained<NSTextField>>,
    status_label: OnceCell<Retained<NSTextField>>,
    detail_label: OnceCell<Retained<NSTextField>>,
    spinner: OnceCell<Retained<NSProgressIndicator>>,

    retry_button: OnceCell<Retained<NSButton>>,
    search_button: OnceCell<Retained<NSButton>>,
    quit_button: OnceCell<Retained<NSButton>>,
    logs_button: OnceCell<Retained<NSButton>>,

    receiver: RefCell<Option<Receiver<AppState>>>,
    worker_running: Cell<bool>,
    cancellation: RefCell<Option<worker::CancellationToken>>,
    primary_action: Cell<PrimaryAction>,

    // Set by the first shutdown request so that one shutdown produces one
    // action, one narrative, and one exit line.
    quitting: Cell<bool>,

    // Shared ownership of the active ffplay child process.
    //
    // The worker thread launches and monitors it.
    // The AppKit thread can terminate it when the user quits PGC.
    player: Arc<Mutex<Option<Child>>>,
}


#[derive(Clone, Copy)]
enum PrimaryAction {
    Retry,
    Cancel,
    Stop,
}


// -----------------------------------------------------------------------------
// AppDelegate
// -----------------------------------------------------------------------------

define_class!(
    #[unsafe(super(NSObject))]
    #[thread_kind = MainThreadOnly]
    #[ivars = AppDelegateIvars]
    struct AppDelegate;

    unsafe impl NSObjectProtocol for AppDelegate {}

    unsafe impl NSApplicationDelegate for AppDelegate {
        #[unsafe(method(applicationDidFinishLaunching:))]
        fn application_did_finish_launching(
            &self,
            _notification: &NSNotification,
        ) {
            self.setup_ui();

            // Development builds only: exercise the keyboard policy through
            // real AppKit event dispatch, without any networking, then exit.
            #[cfg(debug_assertions)]
            if std::env::args().any(|argument| argument == UI_SELF_TEST_FLAG) {
                self.run_ui_self_test();

                return;
            }

            self.start_worker();
            self.start_state_timer();
        }
    }

    unsafe impl NSWindowDelegate for AppDelegate {
        #[unsafe(method(windowWillClose:))]
        fn window_will_close(
            &self,
            _notification: &NSNotification,
        ) {
            // Quit closes the window as part of terminating; that is not a
            // second user action.
            if self.ivars().quitting.get() {
                return;
            }

            logging::action("Window close");

            self.quit_application();
        }
    }

    impl AppDelegate {
        // ---------------------------------------------------------------------
        // Pull state messages from the worker thread
        // ---------------------------------------------------------------------

        #[unsafe(method(pollState:))]
        fn poll_state(
            &self,
            _timer: &NSTimer,
        ) {
            let states: Vec<AppState> = {
                let receiver =
                    self.ivars().receiver.borrow();

                match receiver.as_ref() {
                    Some(receiver) => {
                        receiver.try_iter().collect()
                    }

                    None => Vec::new(),
                }
            };

            for state in states {
                self.render_state(&state);
            }
        }


        // ---------------------------------------------------------------------
        // Retry after an error
        // ---------------------------------------------------------------------

        #[unsafe(method(retry:))]
        fn retry(
            &self,
            _sender: &AnyObject,
        ) {
            if self.ivars().worker_running.get() {
                return;
            }

            logging::action("Retry");

            self.start_worker();
        }


        #[unsafe(method(primaryAction:))]
        fn primary_action(
            &self,
            _sender: &AnyObject,
        ) {
            match self.ivars().primary_action.get() {
                PrimaryAction::Retry => {
                    logging::action("Retry");

                    self.start_worker();
                }

                PrimaryAction::Cancel => {
                    logging::action("Cancel");

                    self.cancel_active_session();
                }

                PrimaryAction::Stop => {
                    logging::action("Stop Stream");

                    self.cancel_active_session();
                }
            }
        }


        // ---------------------------------------------------------------------
        // Search again after playback has ended normally
        // ---------------------------------------------------------------------

        #[unsafe(method(search:))]
        fn search(
            &self,
            _sender: &AnyObject,
        ) {
            if self.ivars().worker_running.get() {
                return;
            }

            logging::action("Search");

            self.start_worker();
        }


        // ---------------------------------------------------------------------
        // Show this session's log directory in Finder
        // ---------------------------------------------------------------------

        #[unsafe(method(openLogs:))]
        fn open_logs(
            &self,
            _sender: &AnyObject,
        ) {
            self.open_logs_folder("button");
        }


        // Sent by MainWindow when the L shortcut is pressed.
        #[unsafe(method(openLogsFromKeyboard:))]
        fn open_logs_from_keyboard(
            &self,
            _sender: &AnyObject,
        ) {
            self.open_logs_folder("keyboard shortcut");
        }


        // Sent by MainWindow the first time it swallows a repeated activation
        // key during one key hold. `key` names the key.
        #[unsafe(method(keyRepeatSuppressed:))]
        fn key_repeat_suppressed(
            &self,
            key: &NSString,
        ) {
            logging::verbose(
                "UI",
                format_args!(
                    "Ignored repeated {key} activation for {} (one activation per key press)",
                    self.focused_button_name()
                ),
            );
        }


        // Sent by MainWindow just before a key press activates the focused
        // button. `key` names the key.
        #[unsafe(method(buttonActivatedByKey:))]
        fn button_activated_by_key(
            &self,
            key: &NSString,
        ) {
            logging::verbose(
                "UI",
                format_args!(
                    "Focused button activated via {key}: {}",
                    self.focused_button_name()
                ),
            );
        }


        // ---------------------------------------------------------------------
        // Quit PGC and terminate ffplay
        // ---------------------------------------------------------------------

        #[unsafe(method(quit:))]
        fn quit(
            &self,
            _sender: &AnyObject,
        ) {
            logging::action("Quit");

            self.quit_application();
        }
    }
);


// -----------------------------------------------------------------------------
// Native UI implementation
// -----------------------------------------------------------------------------

impl AppDelegate {
    fn new(
        mtm: MainThreadMarker,
    ) -> Retained<Self> {
        let this =
            Self::alloc(mtm).set_ivars(AppDelegateIvars {
                window: OnceCell::new(),
                host_label: OnceCell::new(),
                status_label: OnceCell::new(),
                detail_label: OnceCell::new(),
                spinner: OnceCell::new(),

                retry_button: OnceCell::new(),
                search_button: OnceCell::new(),
                quit_button: OnceCell::new(),
                logs_button: OnceCell::new(),

                receiver: RefCell::new(None),
                worker_running: Cell::new(false),
                cancellation: RefCell::new(None),
                primary_action: Cell::new(PrimaryAction::Retry),
                quitting: Cell::new(false),

                player: Arc::new(
                    Mutex::new(None)
                ),
            });

        unsafe {
            msg_send![super(this), init]
        }
    }


    // -------------------------------------------------------------------------
    // Build the native macOS window
    // -------------------------------------------------------------------------

    fn setup_ui(&self) {
        let mtm = self.mtm();

        let app =
            NSApplication::sharedApplication(mtm);


        // ---------------------------------------------------------------------
        // Window
        // ---------------------------------------------------------------------

        let window: Retained<NSWindow> =
            Retained::into_super(
                MainWindow::new(
                    mtm,

                    NSRect::new(
                        NSPoint::new(0.0, 0.0),
                        NSSize::new(
                            WINDOW_CONTENT_WIDTH,
                            WINDOW_CONTENT_HEIGHT,
                        ),
                    ),

                    NSWindowStyleMask::Titled
                        | NSWindowStyleMask::Closable
                        | NSWindowStyleMask::Miniaturizable,
                )
            );

        unsafe {
            window.setReleasedWhenClosed(false);
        }

        window.setTitle(
            ns_string!("Portable Game Caster")
        );

        window.center();

        window.setDelegate(
            Some(
                ProtocolObject::from_ref(self)
            )
        );


        let content = window
            .contentView()
            .expect(
                "PGC window should have a content view"
            );


        // ---------------------------------------------------------------------
        // Title
        // ---------------------------------------------------------------------

        let title_label =
            NSTextField::labelWithString(
                ns_string!("Portable Game Caster"),
                mtm,
            );

        title_label.setFrame(
            NSRect::new(
                NSPoint::new(20.0, 175.0),
                NSSize::new(420.0, 30.0),
            )
        );

        title_label.setAlignment(
            NSTextAlignment::Center
        );

        content.addSubview(&title_label);


        // ---------------------------------------------------------------------
        // Resolved host identity
        // ---------------------------------------------------------------------

        let host_label =
            NSTextField::labelWithString(
                ns_string!(""),
                mtm,
            );

        host_label.setFrame(
            NSRect::new(
                NSPoint::new(20.0, 151.0),
                NSSize::new(420.0, 20.0),
            )
        );

        host_label.setAlignment(
            NSTextAlignment::Center
        );

        host_label.setHidden(true);

        content.addSubview(&host_label);


        // ---------------------------------------------------------------------
        // Primary status
        // ---------------------------------------------------------------------

        let status_label =
            NSTextField::labelWithString(
                ns_string!("Ready"),
                mtm,
            );

        status_label.setFrame(
            NSRect::new(
                NSPoint::new(20.0, 122.0),
                NSSize::new(420.0, 26.0),
            )
        );

        status_label.setAlignment(
            NSTextAlignment::Center
        );

        content.addSubview(&status_label);


        // ---------------------------------------------------------------------
        // Detail text
        // ---------------------------------------------------------------------

        let detail_label =
            NSTextField::wrappingLabelWithString(
                ns_string!(""),
                mtm,
            );

        detail_label.setFrame(
            NSRect::new(
                NSPoint::new(30.0, 86.0),
                NSSize::new(400.0, 30.0),
            )
        );

        detail_label.setAlignment(
            NSTextAlignment::Center
        );

        content.addSubview(&detail_label);


        // ---------------------------------------------------------------------
        // Spinner
        // ---------------------------------------------------------------------

        let spinner =
            NSProgressIndicator::new(mtm);

        spinner.setFrame(
            NSRect::new(
                NSPoint::new(215.0, 55.0),
                NSSize::new(30.0, 30.0),
            )
        );

        spinner.setIndeterminate(true);

        spinner.setStyle(
            NSProgressIndicatorStyle::Spinning
        );

        spinner.setDisplayedWhenStopped(false);

        content.addSubview(&spinner);


        // ---------------------------------------------------------------------
        // Retry button
        //
        // Only visible after an error.
        // ---------------------------------------------------------------------

        let retry_button =
            HoverButton::push_button(
                ns_string!("Retry"),
                self,
                sel!(primaryAction:),
            );

        retry_button.setFrame(
            NSRect::new(
                NSPoint::new(115.0, 15.0),
                NSSize::new(120.0, 32.0),
            )
        );

        retry_button.setHidden(true);

        content.addSubview(&retry_button);


        // ---------------------------------------------------------------------
        // Search button
        //
        // Visible while Idle after playback ends.
        // ---------------------------------------------------------------------

        let search_button =
            HoverButton::push_button(
                ns_string!("Search for Host"),
                self,
                sel!(search:),
            );

        search_button.setFrame(
            NSRect::new(
                NSPoint::new(115.0, 15.0),
                NSSize::new(120.0, 32.0),
            )
        );

        search_button.setHidden(true);

        content.addSubview(&search_button);


        // ---------------------------------------------------------------------
        // Quit button
        // ---------------------------------------------------------------------

        let quit_button =
            HoverButton::push_button(
                ns_string!("Quit"),
                self,
                sel!(quit:),
            );

        quit_button.setFrame(
            NSRect::new(
                NSPoint::new(245.0, 15.0),
                NSSize::new(80.0, 32.0),
            )
        );

        content.addSubview(&quit_button);

        self.ivars()
            .quit_button
            .set(quit_button)
            .expect(
                "quit button should only be initialized once"
            );


        // ---------------------------------------------------------------------
        // Open Logs Folder
        //
        // A small icon in the top-right corner: a support aid, not part of the
        // main flow.
        // ---------------------------------------------------------------------

        let logs_icon =
            NSImage::imageWithSystemSymbolName_accessibilityDescription(
                ns_string!("doc.text"),
                Some(ns_string!("Open Logs Folder")),
            );

        let logs_button = unsafe {
            match logs_icon {
                Some(icon) => NSButton::buttonWithImage_target_action(
                    &icon,
                    Some(self),
                    Some(sel!(openLogs:)),
                    mtm,
                ),

                // No such symbol on this system: fall back to a short title.
                None => NSButton::buttonWithTitle_target_action(
                    ns_string!("Logs"),
                    Some(self),
                    Some(sel!(openLogs:)),
                    mtm,
                ),
            }
        };

        logs_button.setToolTip(
            Some(ns_string!("Open Logs Folder [L]"))
        );

        // The L shortcut is handled by the window (see key_decision), not by a
        // key equivalent on this button, so it does not depend on which
        // control currently has keyboard focus.


        // ---------------------------------------------------------------------
        // Utility shelf
        //
        // A quiet container in the top-right corner for small utility icons.
        // Add a button by raising UTILITY_BUTTON_COUNT and placing it at the
        // next index.
        // ---------------------------------------------------------------------

        let shelf =
            NSBox::initWithFrame(
                NSBox::alloc(mtm),
                utility_shelf_frame(UTILITY_BUTTON_COUNT),
            );

        shelf.setBoxType(NSBoxType::Custom);
        shelf.setTitlePosition(NSTitlePosition::NoTitle);
        shelf.setBorderWidth(0.0);
        shelf.setCornerRadius(8.0);

        shelf.setContentViewMargins(
            NSSize::new(0.0, 0.0)
        );

        // Adapts to light and dark appearance; deliberately faint.
        shelf.setFillColor(
            &NSColor::quaternaryLabelColor()
        );

        content.addSubview(&shelf);


        style_utility_button(&logs_button);

        logs_button.setFrame(
            utility_button_frame(0)
        );

        // The button lives in the shelf's own content view, so its frame is in
        // shelf coordinates. (Adding it to the window content view as well
        // would re-parent it and place it at the window's bottom-left.)
        let shelf_content = shelf
            .contentView()
            .expect(
                "utility shelf should have a content view"
            );

        shelf_content.addSubview(&logs_button);

        report_shelf_placement(
            "OpenLogsFolder",
            &logs_button,
            &shelf_content,
            &shelf,
        );


        // ---------------------------------------------------------------------
        // Retain UI objects used after setup
        // ---------------------------------------------------------------------

        self.ivars()
            .window
            .set(window.clone())
            .expect(
                "window should only be initialized once"
            );

        self.ivars()
            .host_label
            .set(host_label)
            .expect(
                "host label should only be initialized once"
            );

        self.ivars()
            .status_label
            .set(status_label)
            .expect(
                "status label should only be initialized once"
            );

        self.ivars()
            .detail_label
            .set(detail_label)
            .expect(
                "detail label should only be initialized once"
            );

        self.ivars()
            .spinner
            .set(spinner)
            .expect(
                "spinner should only be initialized once"
            );

        self.ivars()
            .retry_button
            .set(retry_button)
            .expect(
                "retry button should only be initialized once"
            );

        self.ivars()
            .search_button
            .set(search_button)
            .expect(
                "search button should only be initialized once"
            );

        self.ivars()
            .logs_button
            .set(logs_button)
            .expect(
                "logs button should only be initialized once"
            );


        // ---------------------------------------------------------------------
        // Show application
        // ---------------------------------------------------------------------

        window.makeKeyAndOrderFront(None);

        // AppKit gives keyboard focus to the first control that accepts it,
        // which made Quit the target of Space/Return at launch. Start with no
        // control focused; Tab still reaches every control deliberately.
        window.makeFirstResponder(None);

        logging::verbose(
            "UI",
            format_args!(
                "Initial focus: none (Tab moves through SearchForHost / Retry / Cancel / StopStream, Quit, OpenLogsFolder as available)"
            ),
        );

        app.setActivationPolicy(
            NSApplicationActivationPolicy::Regular
        );

        #[allow(deprecated)]
        app.activateIgnoringOtherApps(true);
    }


    // -------------------------------------------------------------------------
    // Poll the worker state channel from the AppKit run loop
    // -------------------------------------------------------------------------

    fn start_state_timer(&self) {
        unsafe {
            NSTimer::scheduledTimerWithTimeInterval_target_selector_userInfo_repeats(
                0.1,
                self,
                sel!(pollState:),
                None,
                true,
            );
        }
    }


    // -------------------------------------------------------------------------
    // Start a new discovery / playback worker
    // -------------------------------------------------------------------------

    fn start_worker(&self) {
        if self.ivars().worker_running.get() {
            return;
        }

        self.ivars()
            .worker_running
            .set(true);

        self.render_state(
            &AppState::Discovering {
                seconds_remaining: None,
            }
        );


        let (tx, rx) =
            mpsc::channel::<AppState>();

        *self.ivars()
            .receiver
            .borrow_mut() = Some(rx);


        let player_handle =
            Arc::clone(
                &self.ivars().player
            );


        let cancellation =
            Arc::new(
                AtomicBool::new(false)
            );


        *self.ivars()
            .cancellation
            .borrow_mut() =
            Some(
                Arc::clone(&cancellation)
            );


        thread::spawn(move || {
            worker::run_stream_flow(
                tx,
                player_handle,
                cancellation,
            );
        });
    }


    // -------------------------------------------------------------------------
    // Cancel discovery, connection, recovery, or playback by user request.
    // -------------------------------------------------------------------------

    fn cancel_active_session(&self) {
        if let Some(cancellation) = self
            .ivars()
            .cancellation
            .borrow()
            .as_ref()
        {
            cancellation.store(
                true,
                Ordering::Relaxed,
            );
        }


        self.terminate_player();


        // Dropping the receiver invalidates every pending state from the
        // cancelled worker before a later search starts a fresh session.
        self.ivars()
            .receiver
            .borrow_mut()
            .take();


        self.ivars()
            .worker_running
            .set(false);


        // The cancelled worker can no longer report states, so the UI's
        // return to Idle is logged here. The log must end where the UI does.
        logging::state(&AppState::Idle);

        self.render_state(&AppState::Idle);
    }


    // -------------------------------------------------------------------------
    // Show this session's log directory in Finder
    //
    // `source` is how the user asked: it is only reported in Verbose.
    // -------------------------------------------------------------------------

    fn open_logs_folder(
        &self,
        source: &str,
    ) {
        logging::action("Open Logs Folder");

        logging::verbose(
            "UI",
            format_args!(
                "Open Logs Folder invoked via {source}"
            ),
        );

        let Some(directory) = logging::log_directory() else {
            logging::warn(
                "APP",
                format_args!(
                    "No logs folder to open: this session has no log file."
                ),
            );

            return;
        };


        #[cfg(debug_assertions)]
        if UI_SELF_TEST.with(Cell::get) {
            logging::debug(
                "APP",
                format_args!(
                    "Self-test: not opening Finder."
                ),
            );

            return;
        }


        let url =
            NSURL::fileURLWithPath(
                &NSString::from_str(
                    &directory.to_string_lossy()
                )
            );


        // Asks Finder to show the folder and returns immediately.
        let opened =
            NSWorkspace::sharedWorkspace()
                .openURL(&url);


        if opened {
            logging::debug(
                "APP",
                format_args!(
                    "Opened {}",
                    directory.display()
                ),
            );
        } else {
            logging::warn(
                "APP",
                format_args!(
                    "Could not open logs folder {}",
                    directory.display()
                ),
            );
        }
    }


    // -------------------------------------------------------------------------
    // UI self-test (development builds only)
    //
    // Sends synthetic key events through the real window, so the keyboard
    // policy is exercised by AppKit's own dispatch rather than only by unit
    // tests of the decision function. Starts no discovery and opens nothing.
    // -------------------------------------------------------------------------

    #[cfg(debug_assertions)]
    fn run_ui_self_test(&self) {
        UI_SELF_TEST.with(|flag| flag.set(true));

        let note = |text: &str| {
            logging::info(
                "APP",
                format_args!("Self-test: {text}"),
            );
        };

        let (Some(window), Some(logs_button)) = (
            self.ivars().window.get(),
            self.ivars().logs_button.get(),
        ) else {
            return;
        };

        let key = |kind: NSEventType, characters: &str, is_repeat: bool| {
            let characters =
                NSString::from_str(characters);

            let event = NSEvent::keyEventWithType_location_modifierFlags_timestamp_windowNumber_context_characters_charactersIgnoringModifiers_isARepeat_keyCode(
                kind,
                NSPoint::new(0.0, 0.0),
                NSEventModifierFlags::empty(),
                0.0,
                window.windowNumber(),
                None,
                &characters,
                &characters,
                is_repeat,
                0,
            );

            if let Some(event) = event {
                window.sendEvent(&event);
            }
        };

        let press = |characters: &str| {
            key(NSEventType::KeyDown, characters, false);
            key(NSEventType::KeyUp, characters, false);
        };


        // Optional: render the window contents to PNG files for inspection.
        if let Some(directory) = std::env::var_os("PGC_UI_SNAPSHOT_DIR") {
            self.write_ui_snapshots(
                std::path::Path::new(&directory)
            );
        }


        note("three separate L presses, then Caps Lock L (expect four keyboard invocations)");

        press("l");
        press("l");
        press("l");
        press("L");


        note("L held down with ten repeats (expect one keyboard invocation)");

        key(NSEventType::KeyDown, "l", false);

        for _ in 0..10 {
            key(NSEventType::KeyDown, "l", true);
        }

        key(NSEventType::KeyUp, "l", false);


        note("Space held on a focused button with ten repeats (expect one button invocation and one ignored-repeat line)");

        let responder: &NSResponder =
            logs_button;

        let focused =
            window.makeFirstResponder(Some(responder));

        note(&format!("button accepted keyboard focus: {focused}"));

        key(NSEventType::KeyDown, " ", false);

        for _ in 0..10 {
            key(NSEventType::KeyDown, " ", true);
        }

        key(NSEventType::KeyUp, " ", false);


        note("Space released and pressed again (expect one more button invocation)");

        press(" ");


        note("Return on the focused button (expect one button invocation)");

        press("\r");


        note("Return held with ten repeats (expect one button invocation and one ignored-repeat line)");

        key(NSEventType::KeyDown, "\r", false);

        for _ in 0..10 {
            key(NSEventType::KeyDown, "\r", true);
        }

        key(NSEventType::KeyUp, "\r", false);


        note("keypad Enter on the focused button (expect one button invocation)");

        press("\u{3}");


        note("complete");

        logging::shutdown();

        NSApplication::sharedApplication(self.mtm())
            .terminate(None);
    }


    // Renders the window contents in several states, off screen, so layout and
    // hover / pressed treatment can be inspected without operating the window.
    #[cfg(debug_assertions)]
    fn write_ui_snapshots(
        &self,
        directory: &std::path::Path,
    ) {
        let Some(content) = self
            .ivars()
            .window
            .get()
            .and_then(|window| window.contentView())
        else {
            return;
        };

        // The window's frame view draws the window background behind the
        // content, which the content view alone does not.
        let content =
            unsafe { content.superview() }.unwrap_or(content);

        let snapshot = |name: &str| {
            let bounds =
                content.bounds();

            let Some(bitmap) = content.bitmapImageRepForCachingDisplayInRect(bounds) else {
                return;
            };

            content.cacheDisplayInRect_toBitmapImageRep(
                bounds,
                &bitmap,
            );

            let png = unsafe {
                bitmap.representationUsingType_properties(
                    NSBitmapImageFileType::PNG,
                    &NSDictionary::new(),
                )
            };

            let path =
                directory.join(format!("{name}.png"));

            let written =
                png.is_some_and(|png| {
                    png.writeToFile_atomically(
                        &NSString::from_str(&path.to_string_lossy()),
                        true,
                    )
                });

            logging::info(
                "APP",
                format_args!(
                    "Self-test: snapshot {} written: {written}",
                    path.display()
                ),
            );
        };

        let hover = |button: &NSButton, hovered: bool| {
            if let Some(button) = button.downcast_ref::<HoverButton>() {
                button.set_hovered(hovered);
            }
        };

        let search =
            self.slot_button(SlotControl::Search);

        let primary =
            self.slot_button(SlotControl::Primary);

        let _ = std::fs::create_dir_all(directory);


        self.render_state(&AppState::Idle);
        snapshot("1-idle");

        hover(search, true);
        snapshot("2-idle-search-hovered");

        search.highlight(true);
        snapshot("3-idle-search-hovered-pressed");

        search.highlight(false);
        hover(search, false);

        search.highlight(true);
        snapshot("4-idle-search-pressed-only");
        search.highlight(false);


        self.render_state(&AppState::Playing("carock-pgc.local".into()));
        snapshot("5-playing");

        hover(primary, true);
        snapshot("6-playing-stop-hovered");
        hover(primary, false);


        if let Some(quit) = self.ivars().quit_button.get() {
            hover(quit, true);
            snapshot("7-playing-quit-hovered");
            hover(quit, false);
        }


        // Keyboard focus without hover: the focus ring must be the only
        // difference from the resting button.
        if let Some(window) = self.ivars().window.get() {
            let responder: &NSResponder =
                primary;

            window.makeFirstResponder(Some(responder));
            snapshot("8-playing-stop-focused");
            window.makeFirstResponder(None);
        }


        self.render_state(&AppState::Error("Stream did not start.".into()));
        snapshot("9-error");


        self.render_state(&AppState::Idle);
    }


    // -------------------------------------------------------------------------
    // Quit: stop the session, terminate ffplay, exit
    // -------------------------------------------------------------------------

    fn quit_application(&self) {
        if !begin_shutdown(&self.ivars().quitting) {
            return;
        }

        // Stop the worker from reporting or starting anything further.
        if let Some(cancellation) = self
            .ivars()
            .cancellation
            .borrow()
            .as_ref()
        {
            cancellation.store(
                true,
                Ordering::Relaxed,
            );
        }


        self.terminate_player();


        logging::info(
            "APP",
            format_args!(
                "Portable Game Caster Client exiting."
            ),
        );

        logging::shutdown();


        let app =
            NSApplication::sharedApplication(self.mtm());

        app.terminate(None);
    }


    // -------------------------------------------------------------------------
    // Kill the active ffplay process if one exists
    // -------------------------------------------------------------------------

    fn terminate_player(&self) {
        let mut slot = self
            .ivars()
            .player
            .lock()
            .expect(
                "player process lock poisoned"
            );


        if let Some(child) = slot.as_mut() {
            logging::debug(
                "PLAYER",
                format_args!(
                    "Terminating ffplay PID {}",
                    child.id()
                ),
            );

            let _ = child.kill();
            let _ = child.wait();
        }


        *slot = None;
    }


    // -------------------------------------------------------------------------
    // Render an AppState
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // Render an AppState, keeping keyboard focus sensible
    //
    // Retry / Cancel / Stop Stream and Search for Host share one slot in the
    // window. When a state change hides the focused one, AppKit would hand
    // focus to the next control (Quit). Instead focus follows the slot: to the
    // control that replaced it, or nowhere if nothing did.
    // -------------------------------------------------------------------------

    fn render_state(
        &self,
        state: &AppState,
    ) {
        let focused =
            self.focused_slot_control();

        let previous_name =
            focused.map(|control| self.slot_control_name(control));


        self.apply_state(state);


        let (Some(focused), Some(previous_name)) = (focused, previous_name) else {
            return;
        };

        let decision =
            focus_after_transition(
                focused,
                self.slot_control_visible(SlotControl::Primary),
                self.slot_control_visible(SlotControl::Search),
            );

        let Some(window) = self.ivars().window.get() else {
            return;
        };

        match decision {
            FocusDecision::Keep => {}

            FocusDecision::Transfer(target) => {
                let responder: &NSResponder =
                    self.slot_button(target);

                window.makeFirstResponder(
                    Some(responder)
                );

                logging::verbose(
                    "UI",
                    format_args!(
                        "Focus transferred: {previous_name} -> {} after state transition",
                        self.slot_control_name(target)
                    ),
                );
            }

            FocusDecision::Clear => {
                window.makeFirstResponder(
                    None
                );

                logging::verbose(
                    "UI",
                    format_args!(
                        "Focus cleared: {previous_name} is no longer available and nothing replaced it"
                    ),
                );
            }
        }
    }


    fn slot_button(
        &self,
        control: SlotControl,
    ) -> &NSButton {
        let button = match control {
            SlotControl::Primary => self.ivars().retry_button.get(),
            SlotControl::Search => self.ivars().search_button.get(),
        };

        button.expect(
            "slot buttons should exist"
        )
    }


    fn slot_control_visible(
        &self,
        control: SlotControl,
    ) -> bool {
        !self.slot_button(control).isHidden()
    }


    // What the control is to the user right now.
    fn slot_control_name(
        &self,
        control: SlotControl,
    ) -> &'static str {
        match control {
            SlotControl::Search => "SearchForHost",

            SlotControl::Primary => match self.ivars().primary_action.get() {
                PrimaryAction::Retry => "Retry",
                PrimaryAction::Cancel => "Cancel",
                PrimaryAction::Stop => "StopStream",
            },
        }
    }


    // The button that has keyboard focus, as the user knows it.
    fn focused_button_name(&self) -> &'static str {
        if let Some(control) = self.focused_slot_control() {
            return self.slot_control_name(control);
        }

        let focused =
            self.ivars()
                .window
                .get()
                .and_then(|window| window.firstResponder());

        let is_focused = |button: Option<&Retained<NSButton>>| {
            match (&focused, button) {
                (Some(focused), Some(button)) => {
                    let button: &NSResponder =
                        button;

                    std::ptr::eq(&**focused, button)
                }

                _ => false,
            }
        };

        if is_focused(self.ivars().quit_button.get()) {
            "Quit"
        } else if is_focused(self.ivars().logs_button.get()) {
            "OpenLogsFolder"
        } else {
            "the focused button"
        }
    }


    // Which slot control, if either, currently has keyboard focus.
    fn focused_slot_control(&self) -> Option<SlotControl> {
        let window =
            self.ivars().window.get()?;

        let first_responder =
            window.firstResponder()?;

        let focused: *const NSResponder =
            &*first_responder;

        [SlotControl::Primary, SlotControl::Search]
            .into_iter()
            .find(|control| {
                let button: &NSResponder =
                    self.slot_button(*control);

                std::ptr::eq(focused, button)
            })
    }


    fn apply_state(
        &self,
        state: &AppState,
    ) {
        let host_label = self
            .ivars()
            .host_label
            .get()
            .expect(
                "host label should exist"
            );

        let status_label = self
            .ivars()
            .status_label
            .get()
            .expect(
                "status label should exist"
            );

        let detail_label = self
            .ivars()
            .detail_label
            .get()
            .expect(
                "detail label should exist"
            );

        let spinner = self
            .ivars()
            .spinner
            .get()
            .expect(
                "spinner should exist"
            );

        let retry_button = self
            .ivars()
            .retry_button
            .get()
            .expect(
                "retry button should exist"
            );

        let search_button = self
            .ivars()
            .search_button
            .get()
            .expect(
                "search button should exist"
            );


        if let Some(host) = state.host() {
            host_label.setStringValue(
                &NSString::from_str(
                    &friendly_host_name(host)
                )
            );

            host_label.setHidden(false);
        } else if matches!(
            state,
            AppState::Idle | AppState::Discovering { .. }
        ) {
            host_label.setStringValue(
                ns_string!("")
            );

            host_label.setHidden(true);
        }


        match state {
            // -----------------------------------------------------------------
            // Error
            // -----------------------------------------------------------------

            AppState::Error(error) => {
                status_label.setStringValue(
                    ns_string!("Unable to connect")
                );

                detail_label.setStringValue(
                    &NSString::from_str(error)
                );

                unsafe  {
                    spinner.stopAnimation(None);
                }

                retry_button.setHidden(false);
                search_button.setHidden(true);

                retry_button.setTitle(
                    ns_string!("Retry")
                );

                self.ivars()
                    .primary_action
                    .set(PrimaryAction::Retry);

                self.ivars()
                    .worker_running
                    .set(false);
            }


            // -----------------------------------------------------------------
            // Idle
            // -----------------------------------------------------------------

            AppState::Idle => {
                status_label.setStringValue(
                    ns_string!("Ready")
                );

                detail_label.setStringValue(
                    ns_string!("No active stream.")
                );

                unsafe {
                    spinner.stopAnimation(None);
                }
        

                retry_button.setHidden(true);
                search_button.setHidden(false);

                self.ivars()
                    .worker_running
                    .set(false);
            }


            // -----------------------------------------------------------------
            // Playing
            // -----------------------------------------------------------------

            AppState::Playing(_) => {
                status_label.setStringValue(
                    &NSString::from_str(&state.message())
                );

                detail_label.setStringValue(
                    ns_string!(
                        "Portable Game Caster is live."
                    )
                );

                unsafe {
                    spinner.stopAnimation(None);
                }

                retry_button.setTitle(
                    ns_string!("Stop Stream")
                );

                retry_button.setHidden(false);
                search_button.setHidden(true);

                self.ivars()
                    .primary_action
                    .set(PrimaryAction::Stop);
            }


            // -----------------------------------------------------------------
            // Busy / transitional states
            // -----------------------------------------------------------------

            _ => {
                let message =
                    state.message();

                status_label.setStringValue(
                    &NSString::from_str(
                        &message
                    )
                );

                detail_label.setStringValue(
                    &NSString::from_str(
                        &state.detail_message().unwrap_or_default()
                    )
                );

                retry_button.setTitle(
                    ns_string!("Cancel")
                );

                retry_button.setHidden(false);
                search_button.setHidden(true);

                self.ivars()
                    .primary_action
                    .set(PrimaryAction::Cancel);

                if state.is_busy() {
                    unsafe {
                        spinner.startAnimation(None);
                    }
                } else {
                    unsafe {
                        spinner.stopAnimation(None);
                    }
                }
            }
        }
    }
}


// -----------------------------------------------------------------------------
// Presentation-only mDNS hostname cleanup
// -----------------------------------------------------------------------------

fn friendly_host_name(
    host: &str,
) -> String {
    let trimmed =
        host.trim_end_matches('.');


    let without_local =
        trimmed
            .strip_suffix(".local")
            .unwrap_or(trimmed);


    let without_pgc =
        without_local
            .strip_suffix("-pgc")
            .unwrap_or(without_local);


    if without_pgc.is_empty() {
        trimmed.to_string()
    } else {
        without_pgc.to_ascii_uppercase()
    }
}


// -----------------------------------------------------------------------------
// Application entry point
// -----------------------------------------------------------------------------

pub fn run_app() {
    let mtm =
        MainThreadMarker::new()
            .expect(
                "Portable Game Caster must start on the macOS main thread"
            );


    let app =
        NSApplication::sharedApplication(
            mtm
        );


    let delegate =
        AppDelegate::new(
            mtm
        );


    app.setDelegate(
        Some(
            ProtocolObject::from_ref(
                &*delegate
            )
        )
    );


    app.run();
}


// -----------------------------------------------------------------------------
// Utility shelf layout
//
// Positions are computed, so adding an icon is a matter of raising the count.
// -----------------------------------------------------------------------------

const WINDOW_CONTENT_WIDTH: f64 = 460.0;
const WINDOW_CONTENT_HEIGHT: f64 = 230.0;

// Icons on the shelf today: Open Logs Folder.
const UTILITY_BUTTON_COUNT: usize = 1;

const UTILITY_BUTTON_SIZE: f64 = 24.0;
const UTILITY_BUTTON_GAP: f64 = 4.0;
const UTILITY_SHELF_PADDING: f64 = 5.0;
const UTILITY_SHELF_TOP_MARGIN: f64 = 12.0;
const UTILITY_SHELF_RIGHT_MARGIN: f64 = 14.0;


// The shelf in window content coordinates: hugging the top-right corner and
// growing leftwards as buttons are added.
fn utility_shelf_frame(button_count: usize) -> NSRect {
    let count = button_count.max(1) as f64;

    let width =
        2.0 * UTILITY_SHELF_PADDING
            + count * UTILITY_BUTTON_SIZE
            + (count - 1.0) * UTILITY_BUTTON_GAP;

    let height =
        2.0 * UTILITY_SHELF_PADDING + UTILITY_BUTTON_SIZE;

    NSRect::new(
        NSPoint::new(
            WINDOW_CONTENT_WIDTH - UTILITY_SHELF_RIGHT_MARGIN - width,
            WINDOW_CONTENT_HEIGHT - UTILITY_SHELF_TOP_MARGIN - height,
        ),
        NSSize::new(width, height),
    )
}


// A button's frame inside the shelf, left to right.
fn utility_button_frame(index: usize) -> NSRect {
    NSRect::new(
        NSPoint::new(
            UTILITY_SHELF_PADDING
                + index as f64 * (UTILITY_BUTTON_SIZE + UTILITY_BUTTON_GAP),
            UTILITY_SHELF_PADDING,
        ),
        NSSize::new(UTILITY_BUTTON_SIZE, UTILITY_BUTTON_SIZE),
    )
}


// Shared look for shelf buttons: icon only, with AppKit's own hover treatment
// (the bezel is drawn only while the pointer is inside). Keyboard focus keeps
// its separate system focus ring.
fn style_utility_button(button: &NSButton) {
    button.setBezelStyle(NSBezelStyle::AccessoryBarAction);
    button.setBordered(true);
    button.setShowsBorderOnlyWhileMouseInside(true);
    button.setImagePosition(NSCellImagePosition::ImageOnly);
}


// Checks, at runtime, that a utility button really is a child of the shelf and
// sits inside it. Verbose reports the result; a wrong parent is a warning,
// because the button would then be drawn somewhere else in the window.
fn report_shelf_placement(
    name: &str,
    button: &NSButton,
    shelf_content: &NSView,
    shelf: &NSBox,
) {
    let parent =
        unsafe { button.superview() };

    let parented =
        parent.is_some_and(|parent| std::ptr::eq(&*parent, shelf_content));

    let frame =
        button.frame();

    let inside =
        frame_fits_within(frame, shelf.frame().size);

    if parented && inside {
        logging::verbose(
            "UI",
            format_args!(
                "Utility shelf: {name} is a child of the shelf at ({}, {}) in a {}x{} shelf whose window origin is ({}, {})",
                frame.origin.x,
                frame.origin.y,
                shelf.frame().size.width,
                shelf.frame().size.height,
                shelf.frame().origin.x,
                shelf.frame().origin.y
            ),
        );
    } else {
        logging::warn(
            "APP",
            format_args!(
                "Utility shelf layout problem: {name} parented to shelf: {parented}; inside shelf bounds: {inside}"
            ),
        );
    }
}


// Whether `frame` (in the container's coordinates) lies inside a container of
// `size`.
fn frame_fits_within(frame: NSRect, size: NSSize) -> bool {
    frame.origin.x >= 0.0
        && frame.origin.y >= 0.0
        && frame.origin.x + frame.size.width <= size.width
        && frame.origin.y + frame.size.height <= size.height
}


// -----------------------------------------------------------------------------
// Keyboard focus across state changes
// -----------------------------------------------------------------------------

// The two controls that share the primary action slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SlotControl {
    // Retry / Cancel / Stop Stream.
    Primary,

    // Search for Host.
    Search,
}


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FocusDecision {
    // The focused control is still there.
    Keep,

    // The focused control was replaced in its slot: follow it.
    Transfer(SlotControl),

    // The focused control is gone and nothing took its place.
    Clear,
}


// `focused` had keyboard focus before the transition; the visibility flags
// describe the slot after it.
fn focus_after_transition(
    focused: SlotControl,
    primary_visible: bool,
    search_visible: bool,
) -> FocusDecision {
    let visible = |control| match control {
        SlotControl::Primary => primary_visible,
        SlotControl::Search => search_visible,
    };

    let other = match focused {
        SlotControl::Primary => SlotControl::Search,
        SlotControl::Search => SlotControl::Primary,
    };

    if visible(focused) {
        FocusDecision::Keep
    } else if visible(other) {
        FocusDecision::Transfer(other)
    } else {
        FocusDecision::Clear
    }
}


// -----------------------------------------------------------------------------
// Shutdown
// -----------------------------------------------------------------------------

// True for the first shutdown request only. Quit and window close both end up
// here (terminating also closes the window), and only the first may log and act.
fn begin_shutdown(quitting: &Cell<bool>) -> bool {
    !quitting.replace(true)
}


#[cfg(test)]
mod tests {
    use super::*;


    #[test]
    fn only_the_first_shutdown_request_proceeds() {
        let quitting = Cell::new(false);

        assert!(begin_shutdown(&quitting));

        // Window close arriving as a consequence of Quit, or a second click.
        assert!(!begin_shutdown(&quitting));
        assert!(!begin_shutdown(&quitting));

        assert!(quitting.get());
    }


    fn key(characters: &str, is_repeat: bool, focus: KeyFocus) -> KeyDecision {
        key_decision(&KeyInput {
            characters,
            is_repeat,
            has_command_modifier: false,
            focus,
        })
    }


    #[test]
    fn one_press_activates_and_repeats_are_swallowed() {
        for activation_key in [" ", "\r", "\u{3}"] {
            // The press itself activates the focused button: Space through
            // AppKit, Return / Enter through the window.
            let first_press = if activation_key == " " {
                KeyDecision::PassThrough
            } else {
                KeyDecision::ActivateFocusedButton
            };

            assert_eq!(
                key(activation_key, false, KeyFocus::Button),
                first_press
            );

            // Every repeat while it is held is swallowed, however many arrive
            // and whichever button now has focus.
            for _ in 0..50 {
                assert_eq!(
                    key(activation_key, true, KeyFocus::Button),
                    KeyDecision::SuppressRepeat
                );
            }

            // Released and pressed again: a new press, delivered normally.
            assert_eq!(
                key(activation_key, false, KeyFocus::Button),
                first_press
            );
        }
    }


    #[test]
    fn hover_overlay_covers_the_bezel_without_changing_the_button() {
        // The main buttons: 120x32 and 80x32 frames with a 24pt bezel.
        for width in [120.0, 80.0] {
            let size = NSSize::new(width, 32.0);

            let overlay = hover_overlay_frame(size);

            assert_eq!(overlay.origin.x, 0.0);
            assert_eq!(overlay.origin.y, 4.0);
            assert_eq!(overlay.size.width, width);
            assert_eq!(overlay.size.height, 24.0);

            // Always inside the button: it can never change layout around it.
            assert!(frame_fits_within(overlay, size));
        }

        // A button shorter than the bezel height: exactly the button.
        let short = hover_overlay_frame(NSSize::new(60.0, 18.0));

        assert_eq!(short.origin.y, 0.0);
        assert_eq!(short.size.height, 18.0);
    }


    #[test]
    fn return_and_enter_do_nothing_unless_a_button_is_focused() {
        // No default button: with nothing focused (or something that is not a
        // button) Return / Enter / Space are left entirely to AppKit.
        for focus in [KeyFocus::Window, KeyFocus::Other, KeyFocus::TextInput] {
            for activation_key in [" ", "\r", "\u{3}"] {
                for is_repeat in [false, true] {
                    assert_eq!(
                        key(activation_key, is_repeat, focus),
                        KeyDecision::PassThrough,
                        "{activation_key:?} {focus:?}"
                    );
                }
            }
        }
    }


    #[test]
    fn modified_return_is_not_an_activation() {
        assert_eq!(
            key_decision(&KeyInput {
                characters: "\r",
                is_repeat: false,
                has_command_modifier: true,
                focus: KeyFocus::Button,
            }),
            KeyDecision::PassThrough
        );
    }


    #[test]
    fn repeats_are_left_alone_where_they_cannot_activate_anything() {
        // No button focused: nothing to activate.
        assert_eq!(key(" ", true, KeyFocus::Window), KeyDecision::PassThrough);

        // Other keys repeat normally even on a button (Tab, arrows...).
        assert_eq!(key("\t", true, KeyFocus::Button), KeyDecision::PassThrough);
    }


    #[test]
    fn l_opens_logs_every_press_in_either_case() {
        for focus in [KeyFocus::Window, KeyFocus::Button, KeyFocus::Other] {
            // Repeated separate presses each open the folder.
            for _ in 0..5 {
                assert_eq!(key("l", false, focus), KeyDecision::OpenLogsFolder);
            }

            // Caps Lock or Shift.
            assert_eq!(key("L", false, focus), KeyDecision::OpenLogsFolder);

            // Held down: once, not once per repeat.
            assert_eq!(key("l", true, focus), KeyDecision::SuppressRepeat);
        }
    }


    #[test]
    fn typing_and_modified_keys_are_never_intercepted() {
        for characters in ["l", "L", " ", "\r"] {
            for is_repeat in [false, true] {
                assert_eq!(
                    key(characters, is_repeat, KeyFocus::TextInput),
                    KeyDecision::PassThrough
                );
            }
        }

        // Command-L and friends belong to whatever else handles them.
        assert_eq!(
            key_decision(&KeyInput {
                characters: "l",
                is_repeat: false,
                has_command_modifier: true,
                focus: KeyFocus::Window,
            }),
            KeyDecision::PassThrough
        );
    }


    #[test]
    fn shelf_buttons_fit_inside_the_shelf() {
        for count in 1..=4 {
            let shelf = utility_shelf_frame(count);

            for index in 0..count {
                assert!(
                    frame_fits_within(utility_button_frame(index), shelf.size),
                    "button {index} of {count}"
                );
            }
        }

        // Shelf-relative coordinates applied to the window instead would not
        // be inside the shelf's area of the window.
        let shelf = utility_shelf_frame(1);
        let button = utility_button_frame(0);

        assert!(button.origin.x < shelf.origin.x);
        assert!(button.origin.y < shelf.origin.y);
    }


    #[test]
    fn stop_stream_to_idle_moves_focus_to_search() {
        // Playing -> Idle: Stop Stream hidden, Search for Host shown.
        assert_eq!(
            focus_after_transition(SlotControl::Primary, false, true),
            FocusDecision::Transfer(SlotControl::Search)
        );
    }


    #[test]
    fn search_to_busy_moves_focus_to_cancel() {
        // Idle -> Discovering: Search for Host hidden, Cancel shown.
        assert_eq!(
            focus_after_transition(SlotControl::Search, true, false),
            FocusDecision::Transfer(SlotControl::Primary)
        );
    }


    #[test]
    fn focus_stays_when_the_control_remains() {
        // Cancel -> Stop Stream is the same control with a new title.
        assert_eq!(
            focus_after_transition(SlotControl::Primary, true, false),
            FocusDecision::Keep
        );

        assert_eq!(
            focus_after_transition(SlotControl::Search, false, true),
            FocusDecision::Keep
        );
    }


    #[test]
    fn focus_clears_when_nothing_replaces_the_control() {
        for focused in [SlotControl::Primary, SlotControl::Search] {
            assert_eq!(
                focus_after_transition(focused, false, false),
                FocusDecision::Clear
            );
        }
    }


    #[test]
    fn shelf_hugs_the_top_right_and_grows_leftwards() {
        let one = utility_shelf_frame(1);
        let three = utility_shelf_frame(3);

        // Same right and top edges whatever the button count.
        for shelf in [one, three] {
            assert_eq!(
                shelf.origin.x + shelf.size.width,
                WINDOW_CONTENT_WIDTH - UTILITY_SHELF_RIGHT_MARGIN
            );

            assert_eq!(
                shelf.origin.y + shelf.size.height,
                WINDOW_CONTENT_HEIGHT - UTILITY_SHELF_TOP_MARGIN
            );
        }

        assert_eq!(one.size.width, 34.0);
        assert_eq!(three.size.width, 90.0);
        assert!(three.origin.x < one.origin.x);
    }


    #[test]
    fn shelf_buttons_are_padded_and_do_not_overlap() {
        let shelf = utility_shelf_frame(3);

        let mut previous_right = 0.0;

        for index in 0..3 {
            let button = utility_button_frame(index);

            assert!(button.origin.x >= previous_right);
            assert!(button.origin.x >= UTILITY_SHELF_PADDING);
            assert_eq!(button.origin.y, UTILITY_SHELF_PADDING);

            previous_right = button.origin.x + button.size.width;
        }

        // The last button leaves the same padding on the right.
        assert_eq!(previous_right, shelf.size.width - UTILITY_SHELF_PADDING);
    }
}
